contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #phylonetwork channel"
    url: https://nfcore.slack.com/channels/phylonetwork
    about: Discussion about the nf-core/phylonetwork pipeline
