contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #poecile channel"
    url: https://nfcore.slack.com/channels/poecile
    about: Discussion about the nf-core/poecile pipeline
